CREATE TABLE IF NOT EXISTS users(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	username TEXT NOT NULL,
	hash TEXT NOT NULL,
	cash NUMERIC NOT NULL DEFAULT 10000.00
);

CREATE UNIQUE INDEX username ON users (username);

CREATE TABLE IF NOT EXISTS transactions (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	user_id INTEGER NOT NULL,
	created TEXT NOT NULL,
	company_name TEXT NOT NULL,
	symbol TEXT NOT NULL,
	quantity INTEGER NOT NULL,
	price NUMERIC NOT NULL,

	FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS shares (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	user_id INTEGER NOT NULL,
	company_name TEXT NOT NULL,
	symbol TEXT NOT NULL UNIQUE,
	quantity INTEGER NOT NULL,

	FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE UNIQUE INDEX symbol ON shares (symbol);